# Base image
FROM ubuntu:16.04
MAINTAINER Paul Murrell <paul@stat.auckland.ac.nz>

# add CRAN PPA
RUN apt-get update && apt-get install -y apt-transport-https
RUN echo 'deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/' > /etc/apt/sources.list.d/cran.list
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9

# Install additional software
# R stuff
RUN apt-get update && apt-get install -y \
    r-base=3.6* 

# Dependencies for packages
RUN apt-get update && apt-get install -y \
    libmagick++-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libssh-dev 

# Popper requires a bit more finesse
RUN apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:opencpu/poppler
RUN apt-get update
RUN apt-get install -y libpoppler-cpp-dev

# R packages used in examples
RUN Rscript -e 'install.packages(c("magick", "pdftools", "ssh", "stevedore"))'
RUN Rscript -e 'install.packages("gridBezier")'

# Using COPY will update (invalidate cache) if the tar ball has been modified!
COPY gdiff_0.1-0.tar.gz /tmp/
RUN R CMD INSTALL /tmp/gdiff_0.1-0.tar.gz
# To be replace with things like ...
## RUN Rscript -e 'library(devtools); install_github("pmur002/gdiff@v0.1-0")'

